name: maidenhead
description: The Maidenhead Locator System (a.k.a. QTH Locator and IARU Locator)
             is a geographic co-ordinate system used by amateur radio operators to
             succinctly describe their locations, which replaced the deprecated 
             QRA locator.
version: 0.0.3-dev
homepage: 'https://blackoutcomms.com/'
repository: 'https://github.com/goranskular/maidenhead.git'

environment:
  sdk: '>=2.8.1 <3.0.0'

dev_dependencies:
  test: ^1.14.4
