name: maidenhead
description: The Maidenhead Locator System (a.k.a. QTH Locator and IARU Locator)
             is a geographic co-ordinate system used by amateur radio operators.
version: 0.0.5-dev
homepage: 'https://blackoutcomms.com/'
repository: 'https://github.com/goranskular/maidenhead.git'

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies: 
  #geolocator: 5.3.2+2
  intl: "^0.16.1"
  validate: ^1.7.0

dev_dependencies:
  test: ^1.14.4
